package Vista;

import Controlador.*;
import javax.swing.table.DefaultTableModel;
import proyectofinal.ProyectoFinal;

/**
 *
 * @author Esther SJ
 */
public class Principal extends javax.swing.JFrame {
    
   


    
    public Principal() {
        initComponents();
        

    }
    
  
   

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnRegistrarAlumnos = new javax.swing.JButton();
        bntRegistrarCursos = new javax.swing.JButton();
        btnReporteNotas = new javax.swing.JButton();
        btnRegistrarNotas = new javax.swing.JButton();
        btnReporteNotasXCurso = new javax.swing.JButton();
        btnEditarNotas = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        jPanel2.setBackground(new java.awt.Color(255, 204, 153));

        btnRegistrarAlumnos.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        btnRegistrarAlumnos.setText("Registrar Alumnos en Cursos");
        btnRegistrarAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarAlumnosActionPerformed(evt);
            }
        });

        bntRegistrarCursos.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        bntRegistrarCursos.setText("Registrar Cursos y Alumnos");
        bntRegistrarCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntRegistrarCursosActionPerformed(evt);
            }
        });

        btnReporteNotas.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        btnReporteNotas.setText("Reporte de notas");
        btnReporteNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteNotasActionPerformed(evt);
            }
        });

        btnRegistrarNotas.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        btnRegistrarNotas.setText("Registrar Notas");
        btnRegistrarNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarNotasActionPerformed(evt);
            }
        });

        btnReporteNotasXCurso.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        btnReporteNotasXCurso.setText("Mostrar Notas");
        btnReporteNotasXCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteNotasXCursoActionPerformed(evt);
            }
        });

        btnEditarNotas.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        btnEditarNotas.setText("Editar Notas");
        btnEditarNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarNotasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bntRegistrarCursos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEditarNotas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRegistrarAlumnos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnReporteNotas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRegistrarNotas, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                    .addComponent(btnReporteNotasXCurso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {bntRegistrarCursos, btnEditarNotas, btnRegistrarAlumnos, btnRegistrarNotas, btnReporteNotas, btnReporteNotasXCurso});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntRegistrarCursos)
                    .addComponent(btnRegistrarAlumnos)
                    .addComponent(btnRegistrarNotas))
                .addGap(148, 148, 148)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReporteNotasXCurso)
                    .addComponent(btnReporteNotas)
                    .addComponent(btnEditarNotas, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {bntRegistrarCursos, btnEditarNotas, btnRegistrarAlumnos, btnRegistrarNotas, btnReporteNotas, btnReporteNotasXCurso});

        jLabel1.setFont(new java.awt.Font("Eras Bold ITC", 3, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Bienvenido, Realice sus operaciones!");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 810, Short.MAX_VALUE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarAlumnosActionPerformed
      RegistroAlumnosxcurso raxc = new RegistroAlumnosxcurso();
      raxc.setVisible(true);

    }//GEN-LAST:event_btnRegistrarAlumnosActionPerformed

    private void bntRegistrarCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntRegistrarCursosActionPerformed
        RegistroCursoAlumno rca = new RegistroCursoAlumno();
        rca.setVisible(true);
    }//GEN-LAST:event_bntRegistrarCursosActionPerformed

    private void btnReporteNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteNotasActionPerformed
       ReporteNotaXCurso r = new ReporteNotaXCurso();
       r.setVisible(true);
    }//GEN-LAST:event_btnReporteNotasActionPerformed

    private void btnRegistrarNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarNotasActionPerformed
        RegistroNotasxCurso r = new RegistroNotasxCurso();
        r.setVisible(true);
    }//GEN-LAST:event_btnRegistrarNotasActionPerformed

    private void btnReporteNotasXCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteNotasXCursoActionPerformed
        MostrarNotaxXalumno n =new MostrarNotaxXalumno();
        n.setVisible(true);
    }//GEN-LAST:event_btnReporteNotasXCursoActionPerformed

    private void btnEditarNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarNotasActionPerformed
        EditarNotasXCurso e = new EditarNotasXCurso();
        e.setVisible(true);
    }//GEN-LAST:event_btnEditarNotasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntRegistrarCursos;
    private javax.swing.JButton btnEditarNotas;
    private javax.swing.JButton btnRegistrarAlumnos;
    private javax.swing.JButton btnRegistrarNotas;
    private javax.swing.JButton btnReporteNotas;
    private javax.swing.JButton btnReporteNotasXCurso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
