/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.Alumno;
import Controlador.Curso;
import Controlador.Lista;
import Controlador.nodo;
import javax.swing.table.DefaultTableModel;
import proyectofinal.ProyectoFinal;

/**
 *
 * @author User
 */
public class RegistroCursoAlumno extends javax.swing.JFrame {

    /**
     * Creates new form RegistroCursoAlumno
     */
    public RegistroCursoAlumno() {
        initComponents();
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtnombrecurso = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablacursos = new javax.swing.JTable();
        btnagregarcurso = new javax.swing.JButton();
        btnborrarcurso = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtnombrealum = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaalumno = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        txtapellidopa = new javax.swing.JTextField();
        txtcodigoalum = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtapellidoma = new javax.swing.JTextField();
        btnagregaralum = new javax.swing.JButton();
        btnborraralum = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 153, 102));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 153, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Registros de Cursos y Alumnos");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 12, 336, 43));

        jPanel3.setBackground(new java.awt.Color(255, 231, 140));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtnombrecurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombrecursoActionPerformed(evt);
            }
        });
        jPanel3.add(txtnombrecurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 61, 191, 43));

        jLabel4.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Curso:");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 61, 59, 43));

        jLabel5.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Registro de Cursos");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 198, 43));

        tablacursos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre del curso"
            }
        ));
        jScrollPane1.setViewportView(tablacursos);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 390, 300));

        btnagregarcurso.setText("GUARDAR");
        btnagregarcurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregarcursoActionPerformed(evt);
            }
        });
        jPanel3.add(btnagregarcurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 420, -1, -1));

        btnborrarcurso.setText("ELIMINAR");
        btnborrarcurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnborrarcursoActionPerformed(evt);
            }
        });
        jPanel3.add(btnborrarcurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 51, 410, 460));

        jPanel2.setBackground(new java.awt.Color(153, 255, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Apellido M:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 90, 43));

        jLabel3.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Registro de Alumnos");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 230, 43));

        jLabel6.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Código:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 80, 43));

        txtnombrealum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombrealumActionPerformed(evt);
            }
        });
        jPanel2.add(txtnombrealum, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 130, 43));

        tablaalumno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombres", "Apellido P.", "Apellido M.", "Código"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tablaalumno);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 390, 250));

        jLabel7.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Apellido P:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 90, 43));

        txtapellidopa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtapellidopaActionPerformed(evt);
            }
        });
        jPanel2.add(txtapellidopa, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 90, 43));

        txtcodigoalum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcodigoalumActionPerformed(evt);
            }
        });
        jPanel2.add(txtcodigoalum, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 100, 43));

        jLabel8.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Nombres:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 80, 43));

        txtapellidoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtapellidomaActionPerformed(evt);
            }
        });
        jPanel2.add(txtapellidoma, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 100, 43));

        btnagregaralum.setText("GUARDAR");
        btnagregaralum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregaralumActionPerformed(evt);
            }
        });
        jPanel2.add(btnagregaralum, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 420, -1, -1));

        btnborraralum.setText("ELIMINAR");
        btnborraralum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnborraralumActionPerformed(evt);
            }
        });
        jPanel2.add(btnborraralum, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 420, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, 410, 460));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 878, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtcodigoalumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcodigoalumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodigoalumActionPerformed

    private void txtnombrecursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombrecursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombrecursoActionPerformed

    private void txtnombrealumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombrealumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombrealumActionPerformed

    private void txtapellidopaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtapellidopaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtapellidopaActionPerformed

    private void txtapellidomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtapellidomaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtapellidomaActionPerformed

    private void btnagregaralumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregaralumActionPerformed
        String nombres=txtnombrealum.getText();
        String apellidopa=txtapellidopa.getText();
        String apellidoma=txtapellidoma.getText();
        int code=Integer.parseInt(txtcodigoalum.getText());
        
        Alumno nuevo=new Alumno(nombres, apellidopa, apellidoma, code);
        String[] arreglito={nuevo.getNombres(),nuevo.getApellidop(),nuevo.getApellidom(),String.valueOf(nuevo.getCodigo())};
        
        DefaultTableModel modelo=(DefaultTableModel)tablaalumno.getModel(); //variable para guardar la configuracion de la tabla
        modelo.addRow(arreglito);
        ProyectoFinal.alumnos.InsertarFinal(nuevo);
        txtnombrealum.setText("");
        txtapellidopa.setText("");
        txtapellidoma.setText("");
        txtcodigoalum.setText("");
        ProyectoFinal.alumnos.Mostrar();
    }//GEN-LAST:event_btnagregaralumActionPerformed

    private void btnagregarcursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregarcursoActionPerformed
       String materias=txtnombrecurso.getText();
       Lista<Alumno> alumnosmateria1= new Lista<>();//lista doble enlazada de alumnos del curso, sin nada ya q se agregaran
       //mas adelante
       
       
       Curso nuevocurso=new Curso(materias, alumnosmateria1);
       String[] arreglito={nuevocurso.getCursos()};
       DefaultTableModel modelo=(DefaultTableModel)tablacursos.getModel(); //variable para guardar la configuracion de la tabla
        modelo.addRow(arreglito);
        ProyectoFinal.cursitos.InsertarFinal(nuevocurso);
        txtnombrecurso.setText("");
        ProyectoFinal.cursitos.Mostrar();
    }//GEN-LAST:event_btnagregarcursoActionPerformed

    private void btnborraralumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnborraralumActionPerformed
        if(tablaalumno.getSelectedRow()>=0){
            DefaultTableModel modelo=(DefaultTableModel)tablaalumno.getModel(); //variable para guardar la configuracion de la tabla
        ProyectoFinal.alumnos.Eliminar(tablaalumno.getSelectedRow());
            modelo.removeRow(tablaalumno.getSelectedRow());
            ProyectoFinal.alumnos.Mostrar();
            
            
        }
        //para verificar si se elimino
        nodo<Alumno> actual= ProyectoFinal.alumnos.inicio;
            while(actual != null){
                System.out.println(actual.dato.toString());
                actual= actual.siguiente;
            }
    }//GEN-LAST:event_btnborraralumActionPerformed

    private void btnborrarcursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnborrarcursoActionPerformed
        if(tablacursos.getSelectedRow()>=0){
            DefaultTableModel modelo=(DefaultTableModel)tablacursos.getModel(); //variable para guardar la configuracion de la tabla
        ProyectoFinal.cursitos.Eliminar(tablacursos.getSelectedRow());
            modelo.removeRow(tablacursos.getSelectedRow());
            
            ProyectoFinal.cursitos.Mostrar();                        
        }
        
        //para verificar si se elimino
        nodo<Curso> actual= ProyectoFinal.cursitos.inicio;
        while(actual != null){
            System.out.println(actual.dato.getCursos());
            actual= actual.siguiente;            
        }
    }//GEN-LAST:event_btnborrarcursoActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
       
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroCursoAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroCursoAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroCursoAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroCursoAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroCursoAlumno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnagregaralum;
    private javax.swing.JButton btnagregarcurso;
    private javax.swing.JButton btnborraralum;
    private javax.swing.JButton btnborrarcurso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablaalumno;
    private javax.swing.JTable tablacursos;
    private javax.swing.JTextField txtapellidoma;
    private javax.swing.JTextField txtapellidopa;
    private javax.swing.JTextField txtcodigoalum;
    private javax.swing.JTextField txtnombrealum;
    private javax.swing.JTextField txtnombrecurso;
    // End of variables declaration//GEN-END:variables
}
